# Generated by Django 5.0.3 on 2024-04-04 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_cart_products_cart_cart_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_product',
        ),
    ]
