# Generated by Django 5.0.3 on 2024-03-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='provider',
            name='company',
            field=models.CharField(default='', max_length=200),
        ),
    ]
