# Generated by Django 5.0.3 on 2024-04-04 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_cart_cart_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='carts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.cart'),
        ),
    ]
