# Generated by Django 5.0.3 on 2024-04-04 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_cartproduct_quantity_cartproduct_quantity_wise_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='quantity_wise_price',
        ),
    ]
