# Generated by Django 5.0.3 on 2024-04-16 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_commentreply_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.basemodel')),
                ('country', models.CharField()),
                ('city', models.CharField()),
                ('postal_code', models.IntegerField()),
                ('address_p', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('product.basemodel',),
        ),
        migrations.CreateModel(
            name='checkout',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.basemodel')),
                ('address_p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.address')),
                ('cart_p', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.cart')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('product.basemodel',),
        ),
    ]
