# Generated by Django 5.0.3 on 2024-04-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_address_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
