# Generated by Django 5.0.3 on 2024-04-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_checkout_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
