# Generated by Django 5.0.3 on 2024-04-16 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_address_address_p_alter_address_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
    ]
